const data = {
  products: [
    {
      name: 'Nike T-Shirt',
      slug: 'Nike-t-shirt',
      category: 'Shirt',
      image: './images/p1.jpg',
      price: 200,
      countInStock: 40,
      brand: 'Nike',
      rating: 4.5,
      numReview: 10,
      description: 'This is t shirt with 4 different colors by nike officials',
    },
    {
      name: 'Nike T2-Shirt',
      slug: 'Nike-t3-shirt',
      category: 'Shirt',
      image: './images/p2.jpg',
      price: 200,
      countInStock: 40,
      brand: 'Nike',
      rating: 4.5,
      numReview: 10,
      description: 'This is t shirt with 4 different colors by nike officials',
    },
    {
      name: 'Pent Ts',
      slug: 'nike pent',
      category: 'Pents',
      image: './images/p3.jpg',
      price: 200,
      countInStock: 40,
      brand: 'Nike',
      rating: 4.5,
      numReview: 10,
      description: 'This is t shirt with 4 different colors by nike officials',
    },
    {
      name: 'Addidas Short',
      slug: 'Addidas shorts',
      category: 'Shirt',
      image: './images/p4.jpg',
      price: 200,
      countInStock: 40,
      brand: 'Nike',
      rating: 4.5,
      numReview: 10,
      description: 'This is t shirt with 4 different colors by nike officials',
    },
  ],
};

export default data;
